// <auto-generated />
using System;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(PizzaDBContext))]
    [Migration("20200128195824_P1_Migration")]
    partial class P1_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("orderID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnName("cost")
                        .HasColumnType("money");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnName("orderTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PizzaAmount")
                        .HasColumnName("pizzaAmount")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnName("storeID")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnName("userID")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__0809337D22E4B8F6");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders","Pizza_Schema");
                });

            modelBuilder.Entity("Domain.Models.Pizzas", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pizzaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Crust")
                        .IsRequired()
                        .HasColumnName("crust")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("OrderId")
                        .HasColumnName("orderID")
                        .HasColumnType("int");

                    b.Property<decimal>("PizzaCost")
                        .HasColumnName("pizzaCost")
                        .HasColumnType("money");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnName("size")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("PizzaId")
                        .HasName("PK__Pizzas__4D4C90CF900AAF91");

                    b.HasIndex("OrderId");

                    b.ToTable("Pizzas","Pizza_Schema");
                });

            modelBuilder.Entity("Domain.Models.Stores", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("storeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnName("storeCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnName("storeName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("StoreId")
                        .HasName("PK__Stores__1EA716331174CC67");

                    b.HasIndex("StoreName")
                        .IsUnique()
                        .HasName("UQ__Stores__0E3E451D96309586");

                    b.ToTable("Stores","Pizza_Schema");
                });

            modelBuilder.Entity("Domain.Models.Toppings", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("toppingID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PizzaId")
                        .HasColumnName("pizzaID")
                        .HasColumnType("int");

                    b.Property<string>("Topping")
                        .HasColumnName("topping")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("ToppingId")
                        .HasName("PK__Toppings__AAE1560922457C0E");

                    b.HasIndex("PizzaId");

                    b.ToTable("Toppings","Pizza_Schema");
                });

            modelBuilder.Entity("Domain.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("StoreId")
                        .HasColumnName("storeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StoreTime")
                        .HasColumnName("storeTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnName("userCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("userName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("UserId")
                        .HasName("PK__Users__CB9A1CDF1FD5E7CF");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasName("UQ__Users__66DCF95C7BBEC8C5");

                    b.ToTable("Users","Pizza_Schema");
                });

            modelBuilder.Entity("Domain.Models.Orders", b =>
                {
                    b.HasOne("Domain.Models.Stores", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .HasConstraintName("FK__Orders__storeID__1CBC4616")
                        .IsRequired();

                    b.HasOne("Domain.Models.Users", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Orders__userID__1DB06A4F")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Pizzas", b =>
                {
                    b.HasOne("Domain.Models.Orders", "Order")
                        .WithMany("Pizzas")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Pizzas__orderID__208CD6FA")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Toppings", b =>
                {
                    b.HasOne("Domain.Models.Pizzas", "Pizza")
                        .WithMany("Toppings")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK__Toppings__pizzaI__236943A5")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Users", b =>
                {
                    b.HasOne("Domain.Models.Stores", "Store")
                        .WithMany("Users")
                        .HasForeignKey("StoreId")
                        .HasConstraintName("FK__Users__storeID__19DFD96B");
                });
#pragma warning restore 612, 618
        }
    }
}
